---
page_name: Вопросы и Ответы
page_url: https://otvet.mail.ru/question/216156098
q_header: //h1[@class='q--qtext']/text()
q_author: //a[@class='q--user']/b/text()
q_body: //div[@class='q--qcomment']/text()
q_like: //span[@class='totalmarks']/text()
q_answer_count: //strong[@class='h-title--b']/text()
a_author: //a[@class='author']/b/text()
a_body: //div[@class='a--atext-value']/text()